- .github/pull_request_template.md
Create a PR template for future PRs
> pr-template

- assests/content/static/template.php
- style-template.css
- view_profile/style-view_profile.css
- view_profile/view_profile.php
- welcome.php
The purpose of this PR is to fix #5 
Removing the link issue
- [x ] I created this pull request for the issue that was assigned to me
- [x ] I have performed a self-review of my own code
> Removing link issue

- connection.php
- index.php
> new commit

- connection.php
- view_profile/style-view_profile.css
- view_profile/view_profile.php
The purpose of this PR is to fix #13
> View Profile user data update

- style-welcome.css
> fixed bottom bar

- assests/content/static/template.php
- style-template.css
The purpose of this PR is to fix #18
Implement smooth animations for the navigation bar transitions.
- Added CSS animations to the navigation bar for transitions such as hover effects, and color changes.
> Navigation Bar Animation

- MembershipSection/library_mem/style-library_mem.css
- MembershipSection/recreation_mem/recreation_mem.php
- MembershipSection/recreation_mem/request_rec.php
- MembershipSection/recreation_mem/style-recreation_mem.css
- connection.php
Adding the Recreation page with its database connection. Now we can see a success notification when the user enters his username, name, and password.
> Recreation Page with database connection

- MembershipSection/library_mem/library_mem.php
- MembershipSection/library_mem/style-library_mem.css
- MembershipSection/recreation_mem/recreation_mem.php
- MembershipSection/recreation_mem/style-recreation_mem.css
- style-welcome.css
Making library membership and recreation membership pages responsively.
https://github.com/Cyber-III/Student-Management-System/assets/142712365/3def32d5-d71b-45e9-a8d3-2dce925a2ad0
https://github.com/Cyber-III/Student-Management-System/assets/142712365/ae9eec92-03e4-4a05-a78d-86dbb74b78ca
> Responsive lib mem & rec mem pages

- view_profile/style-view_profile.css
- view_profile/view_profile.php
Profile view UI is updated to be response to devices.
> Profile view Updated with responsive UI

- Course Modules/course_module.php
- Course Modules/style-courseModule.css
- assests/content/static/template.php
Course Module Page is created with a tempory Table.
- [] I created this pull request for the issue that was assigned to me
> Course Module page update with Module Table

- Class Schedule/classSchedule.php
- Class Schedule/style.css
The purpose of this PR is to modify the class schedule page
https://github.com/Cyber-III/Student-Management-System/assets/142712365/a65f909b-6203-4621-92d7-4eb3630d23b2
> Modifying the Class Schedule Page

- Course Modules/course_module.php
- Course Modules/style-courseModule.css
Course Module Update with every course
> Course Module Update with every course

- LibrarySection/ManageReservedBooks/delete_reservation.php
- LibrarySection/ManageReservedBooks/manageReservedBooks.php
- LibrarySection/ManageReservedBooks/style-manageReservedBooks.css
- PenaltySection/penalty.php
- PenaltySection/style.css
- assests/content/static/template.php
The purpose of this PR is to develop Manage Resereved Books page
https://github.com/Cyber-III/Student-Management-System/assets/142712365/3aa85653-316b-4221-874a-22abdc6400eb
> Manage Reserved Books page

- AssignmentSection/Feedback/feedback.php
- AssignmentSection/Mitigation Request/Add request/addRequest.php
- AssignmentSection/Mitigation Request/view request/viewRequest.php
- AssignmentSection/schedule/schedule.php
- AssignmentSection/submission/submission.php
- Class Schedule/classSchedule.php
- Class Schedule/style.css
- Course Modules/course_module.php
- Course Modules/style-courseModule.css
- assests/content/static/template.php
"Assignment Schedule page update with testing database table"
https://github.com/Cyber-III/Student-Management-System/assets/162031145/274be382-80c6-4bb1-ad88-b21cf636c6d5
> Assignment Schedule page update with testing database table

- VacancySection/apply.php
- VacancySection/style-vacancy.css
- VacancySection/vacancy.php
- assests/content/static/template.php
The purpose of this PR is to develop the Vacancy page
https://github.com/Cyber-III/Student-Management-System/assets/142712365/4447e296-16f7-48d3-9bae-439907f87540
> Developing the Vacancy page

- ExamSection/ExamSchedule/exam_schedule-style.css
- ExamSection/ExamSchedule/exam_schedule.php
- assests/content/static/template.php
The purpose of this PR is to develop the Exam Schedule Page
> Developing the exam schedule page

- admin/ExamSection/ExamSchedule/exam_schedule.php
- admin/ExamSection/ExamSchedule/exam_scheduleSubmission.php
- admin/ExamSection/ExamSchedule/exam_scheduleUpdateDelete.php
- admin/ExamSection/ExamSchedule/style-exam_schedule.css
- admin/assests/content/static/template.php
The purpose of this PR is to develop the Exam Schedule Page (Admin Section)
https://github.com/Cyber-III/Student-Management-System/assets/142712365/075eb93d-6c08-4f04-ba99-5143ec4421a9
> Developing the Exam Schedule page in Admin Section 

- LibrarySection/ManageReservedBooks/manageReservedBooks.php
- LibrarySection/ManageReservedBooks/style-manageReservedBooks.css
- LibrarySection/ReserveBooks/reserveBooks.php
- LibrarySection/ReserveBooks/style-reserveBooks.css
The purpose of this PR is to fix #70  and #71 
Reserved Books
Manage Reserved Books
> Make responsive Library Pages

- AssignmentSection/Mitigation Request/mitigation.php
- AssignmentSection/Mitigation Request/style-mitigation.css
- AssignmentSection/Mitigation Request/style-view_mitigation.css
- AssignmentSection/Mitigation Request/view_mitigation.php
- AssignmentSection/schedule/schedule.php
- AssignmentSection/schedule/style-schedule.css
- LibrarySection/ReserveBooks/reserveBooks.php
- ResultSection/Final/final.php
- ResultSection/Final/style-final.css
- assests/content/static/template.php
- style-template.css
- view_profile/view_profile.php
The purpose of this PR is to finalize the Student's Side
> Finalize the Student's Side

- assests/content/static/template.php
The purpose of this PR is to fix #99 
Removing unnecessary drop-down menus
https://github.com/Cyber-III/Student-Management-System/assets/162031145/b9f547ee-0d0f-4b5f-82ec-29a805cdbc83
> Removing unnecessary drop-down menus

- admin/assests/content/static/template.php
- assests/content/static/template.php
The purpose of this PR is to fix #99
> Removing unnecessary drop-down menus(Admin)

- assests/content/static/template.php
The purpose of this PR is to fix #98 
Class Schedule page need to be in upper section in the Templete
> Class Schedule page need to be in upper section in the Templete

- admin/course Materials/add_material.php
- admin/course Materials/coursematerials.php
- admin/course Materials/delete_material.php
- admin/course Materials/edit_material.php
- admin/course Materials/search_materials.php
- admin/course Materials/style-course_materials.css
The purpose of this PR is to fix #95
> Fixed Course Material page alignment issue

- admin/assests/content/static/template.php
- admin/membership/library/library.php
- admin/membership/library/style-library.css
- admin/membership/recreation/recreation.php
- admin/membership/recreation/style-recreation.css
The purpose of this PR is to develop the Membership pages
> Develop the Membership pages

- admin/style-welcome.css
- admin/welcome.php
This pull request introduces the initial version of the admin dashboard module for the student management system. It includes essential features such as user management, student enrollment tracking, and data visualization tools to empower administrators in managing the system efficiently. 
https://github.com/Cyber-III/Student-Management-System/assets/140915682/126d4a50-0951-46c4-92b0-31719dec6e61
> Developing the Admin Dashboard

- admin/course Materials/add_material.php
- admin/course Materials/coursematerials.php
- admin/course Materials/edit_material.php
The purpose of this PR is to fix #113 
https://github.com/Cyber-III/Student-Management-System/assets/162031145/e8b691aa-9c8a-4167-a9e1-0eda70219bcc
> Admin couse material page fixed

- admin/add-result/result.css
- admin/add-result/result.php
- admin/assests/content/static/template.php
> Add result section

- admin/assests/content/static/template.php
- admin/library/insert/book_updateDelete.php
- admin/library/insert/booksubmission.php
- admin/library/insert/insertBooks.php
- admin/library/insert/style-insertBooks.css
The purpose of this PR is to develop the Book Insertion Page
> Book Insertion Page

- admin/AssignmentSection/mitigation requests/mitigation.php
- admin/AssignmentSection/mitigation requests/style-mitigation.css
- admin/AssignmentSection/mitigation requests/update_status.php
- admin/assests/content/static/template.php
Mitigation Request Accessing page developed (Admin)
https://github.com/Cyber-III/Student-Management-System/assets/162031145/bf9d38d4-49b1-4acd-9dfb-37be8950f23c
> Mitigation Request Accessing page developed (Admin)

- admin/assests/content/static/template.php
- admin/payment/payment_plan/paymentsubmission.php
- admin/payment/payment_plan/plan.css
- admin/payment/payment_plan/plan.php
- admin/payment/payment_plan/search_student.php
- admin/payment/payment_plan/update_delete_student.php
The purpose of this PR is to develop the Manage Payment Plan page
https://github.com/Cyber-III/Student-Management-System/assets/142712365/89d476f9-d9c6-4da4-ae2a-f51ae1ef32dd
> Manage Payment Plan page

- admin/Course modules/add_module.php
- admin/Course modules/delete_module.php
- admin/Course modules/edit_module.php
- admin/Course modules/search_module.php
- admin/Course modules/style-module.css
- admin/assests/content/static/template.php
Admin course module page developed
https://github.com/Cyber-III/Student-Management-System/assets/162031145/59256d94-50a7-4291-9400-d6596f2f6998
> Admin course module page developed

- admin/Add-result/add-mark.css
- admin/Add-result/add-mark.php
- admin/Add-result/process_result.php
- admin/Add-result/result.css
- admin/Add-result/result.php
Update Add Result Page Backend. In the add result page have only frontend. Now i create the backend part of it.
https://github.com/Cyber-III/Student-Management-System/assets/140915682/2ba4e2bd-2ea0-4965-a378-5a96d30f2054
> Update Add Result Page Backend

- admin/Course modules/add_module.php
- admin/Course modules/edit_module.php
- admin/Course modules/modules.php
- admin/Course modules/search_modules.php
- admin/Course modules/style-module.css
Admin course module (course field updated)
> Admin course module (course field updated)

- admin/assests/content/static/template.php
- admin/class schedule/add_schedule.php
- admin/class schedule/class_schedule.php
- admin/class schedule/delete_schedule.php
- admin/class schedule/edit_schedule.php
- admin/class schedule/search_schedules.php
Admin class Schedule page developed
> Admin class Schedule page developed

- admin/Add notice/add notice.css
- admin/Add notice/add notice.php
- admin/assests/content/static/template.php
> Add notice page

- viva/exam_submission.php
- viva/viva.php
The purpose of this PR is to Show the relevant details on the Viva page
https://github.com/Cyber-III/Student-Management-System/assets/142712365/2c850733-b0c4-42be-933f-0578a59e91c3
> Show the relevant details on the Viva page

- admin/Add-result/add-mark.css
- admin/Add-result/add-mark.php
Create the Add-Mark Page Coursework Table. This table is shown the students coursework documents.
https://github.com/Cyber-III/Student-Management-System/assets/140915682/53db9b59-2d0d-4573-9e93-22ac3e700c66
> Create the Add-Mark Page Coursework Table

- admin/assests/content/static/template.php
- admin/class schedule/add_schedule.php
- admin/class schedule/class_schedule.php
- admin/class schedule/delete_schedule.php
- admin/class schedule/edit_schedule.php
- admin/class schedule/search_schedules.php
- admin/class schedule/style-class_schedule.css
Admin Class Schedule page Completed
Admin section
https://github.com/Cyber-III/Student-Management-System/assets/162031145/c06f6a1d-15e8-4305-8e25-7e4fe7635707
Student Section
> Admin Class Schedule page Completed

- admin/Add-result/add-mark.css
- admin/Add-result/add-mark.php
- admin/Add-result/process_result.php
Add the Sucessfull Message and Result Save to Database
https://github.com/Cyber-III/Student-Management-System/assets/140915682/029b5c7b-7e10-4589-adcc-13ffd6076541
> Add the Sucessfull Message and Result Save to Database.

- admin/Add notice/add notice.css
- admin/Add notice/add notice.php
Add batch section for add notice page
> Select  batch for add notice page

- admin/addBatch/batch_manage.php
- admin/addBatch/studentSearch.php
- admin/addBatch/style-studentSearch.css
The purpose of this PR is to Update the adding batches page
> Update the adding batches page

- admin/Add-result/result.css
- admin/Add-result/result.php
The purpose of this PR is to Update Add Result Page
> Update Add Result Page

- Notice-Board-Section/noticeboard.php
- welcome.php
The purpose of this PR is to Update the Notice page and welcome page
> Update the Notice page and welcome page

- admin/Add-result/add-mark.php
- admin/Add-result/process_result.php
- admin/Add-result/result.css
- admin/Add-result/result.php
The purpose of this PR is to Update Database Connection. Assignment results save in assignment table in database and final_result table update.
https://github.com/Cyber-III/Student-Management-System/assets/140915682/4662efcd-437c-4782-a833-205e70d96651
**Assignment Results Update in Assignment Table**
**Final Results Update in Final Result Table**
> Update Database Connection

- Notice-Board-Section/noticeboard.php
- admin/Add notice/add notice.css
- admin/Add notice/add notice.php
- admin/Add notice/batch-notice.php
- admin/Add notice/notice.php
- welcome.php
The purpose of this PR is to Finalize the notice board
> Finalize the notice board

- admin/Course modules/modules.php
- admin/Course modules/style-module.css
I revised the HTML format, fixed minor alignment issues, and ensured it is responsive.
https://github.com/Cyber-III/Student-Management-System/assets/154523455/01fdcf63-d825-4816-8953-809fd9e96387
- [🟢] I created this pull request for the issue that was assigned to me
- [🟢] I have performed a self-review of my own code
- [🟢] I have commented on my code, particularly in hard-to-understand areas
> modifying the module section of Admin

- admin/viva/delete_date.php
- admin/viva/delete_record.php
- admin/viva/save_changes.php
- admin/viva/team.php
- admin/viva/update_date.php
- admin/viva/viva.css
- viva/submit.php
The purpose of this PR is to Update the Viva Page - both sides
> Update the Viva Page - both sides

- admin/Add-result/add-mark.css
- admin/Add-result/add-mark.php
- admin/Add-result/get_results.php
The purpose of this PR is to Add the view results table. After click the view result button and shown the all results for selected student-Id
https://github.com/Cyber-III/Student-Management-System/assets/140915682/087bc8c6-e8d9-4cc7-a201-6c6286a1fd06
> Add the view results table

- PaymentSection/upload_paymentReceipt/check.css
- PaymentSection/upload_paymentReceipt/check.php
- viva/exam_submission-style.css
- viva/exam_submission.php
- viva/viva.css
- viva/viva.php
makes it responsive and style it with CSS
Design the layout to be responsive across all devices and improve its visual appeal by styling it with CSS.
https://github.com/Cyber-III/Student-Management-System/assets/154523455/20b3d733-38d3-43a4-a587-9a54db7449f9
- [🟢] I created this pull request for the issue that was assigned to me
- [🟢] I have performed a self-review of my own code
- [🟢] I have commented on my code, particularly in hard-to-understand areas
> update viva section of the student

- PaymentSection/upload_paymentReceipt/check.css
- PaymentSection/upload_paymentReceipt/check.php
- admin/addBatch/style-studentSearch.css
- admin/class schedule/add_schedule.php
- viva/exam_submission-style.css
- viva/exam_submission.php
- viva/viva.css
- viva/viva.php
makes it responsive and style it with CSS
Design the layout to be responsive across all devices and improve its visual appeal by styling it with CSS.
- [🟢] I created this pull request for the issue that was assigned to me
- [🟢] I have performed a self-review of my own code
- [🟢] I have commented on my code, particularly in hard-to-understand areas
> responsive the check.php 

- admin/Add-result/add-mark.css
- admin/Add-result/add-mark.php
- admin/Add-result/process_result.php
The purpose of this PR is to Adding feedback form
https://github.com/Cyber-III/Student-Management-System/assets/140915682/9c8325e5-7b03-4271-b7fd-fe8cc03b7f5b
> Adding feedback form

- PaymentSection/upload_paymentReceipt/check.css
- PaymentSection/upload_paymentReceipt/check.php
- admin/addBatch/style-studentSearch.css
- admin/class schedule/add_schedule.php
- viva/exam_submission-style.css
- viva/exam_submission.php
- viva/viva.css
- viva/viva.php
makes it responsive and style it with CSS
Design the layout to be responsive across all devices and improve its visual appeal by styling it with CSS.
- [🟢] I created this pull request for the issue that was assigned to me
- [🟢] I have performed a self-review of my own code
- [🟢] I have commented on my code, particularly in hard-to-understand areas
> updating studentsearch and add_schedule

- PaymentSection/upload_paymentReceipt/check.css
- PaymentSection/upload_paymentReceipt/check.php
- admin/addBatch/style-studentSearch.css
- admin/class schedule/add_schedule.php
- style-welcome.css
- viva/exam_submission-style.css
- viva/exam_submission.php
- viva/viva.css
- viva/viva.php
- welcome.php
Adding a side floating button so we can see the notice board only by clicking it, this floating button will only appear when the screen is less than or equal to 760px
https://github.com/Cyber-III/Student-Management-System/assets/154523455/b37faa5e-10a2-4bd7-a2b3-57da2a1b21a8
- [🚀] I created this pull request for the issue that was assigned to me
- [🚀] I have performed a self-review of my own code
- [🚀] I have commented on my code, particularly in hard-to-understand areas
> Modifying the notce board

- index1.php
index1.php file UI updated with responsiveness
> index1.php file UI updated with responsiveness

- AssignmentSection/submission/upload_submission.php
- admin/assests/content/static/template.php
- admin/course Materials/add_material.php
- admin/course Materials/get_modules.php
- assests/content/static/template.php
The purpose of this PR is to update the Material and assignment page update
> Material and assignment pages update

- Lecturer/assests/content/static/template.php
The purpose of this PR is to fix #217
> Lecturer side doctype issue

- admin/EvaluationSection/style-evaluation.css
the main table was covered by the template. now it fixed
> lecturer main body alignments fixed

- Lecturer/Course modules/modules.php
- Lecturer/Course modules/search_modules.php
- Lecturer/Course modules/style-module.css
- Lecturer/assests/content/static/template.php
Lecturer course modules page developed
https://github.com/Cyber-III/Student-Management-System/assets/162031145/ef2c4dfe-0fce-4aa5-9f6e-a45b2f511629
> Lecturer course modules page developed

- Lecturer/studentSearch/studentSearch.php
- admin/addBatch/batch_createdelete.php
- admin/addBatch/batch_manage.php
- admin/addCourse/batch_createdelete.php
- admin/addCourse/batch_manage.php
- admin/addLecs/batch_create.php
- admin/addLecs/batch_manage.php
- admin/addStudent/studentSubmission.php
- admin/graduation/payment_plan/delete_grad.php
- admin/graduation/payment_plan/paymentsubmission.php
- admin/graduation/payment_plan/update_grad.php
The purpose of this PR is to Set the root paths correctly
> Setting the root paths correctly
